# Generated by Django 5.0.6 on 2024-08-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='manger_name',
            new_name='manager_name',
        ),
    ]
