# Generated by Django 5.0.6 on 2024-08-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_manger_name_customer_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
