# Generated by Django 5.0.6 on 2024-08-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidapplyoptions',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='androidinspectresult',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inspectionrecord',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inspectionrecord',
            name='inspection_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='iosapplyoptions',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='iosinspectresult',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
