# Generated by Django 5.0.6 on 2024-08-06 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_androidapplyoptions_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='manager_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.manager', to_field='name'),
        ),
    ]
