# Generated by Django 5.0.6 on 2024-08-08 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_customer_manager_name_customer_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='inspectionschedule',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', to_field='name'),
        ),
    ]
