# Generated by Django 5.0.6 on 2024-08-01 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidInspectResult',
            fields=[
                ('package_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=30, null=True)),
                ('rooting_test', models.BooleanField(default=False)),
                ('rooting', models.BooleanField(default=False)),
                ('integrity', models.BooleanField(default=False)),
                ('emulator', models.BooleanField(default=False)),
                ('obfuscate', models.BooleanField(default=False)),
                ('decompile', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'android_inspect_result',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomerList',
            fields=[
                ('customer_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=30)),
                ('append_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CustomerList',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Managerlist',
            fields=[
                ('user_id', models.CharField(max_length=30)),
                ('manager_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('append_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ManagerList',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('customer_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Monthly',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_name', models.OneToOneField(db_column='package_name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='customer.androidinspectresult')),
                ('license_expire_date', models.DateField(blank=True, null=True)),
                ('append_date', models.DateField(blank=True, null=True)),
                ('os_type', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_name', models.ForeignKey(db_column='customer_name', on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customerlist')),
            ],
            options={
                'db_table': 'Packages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inspectiondocuments',
            fields=[
                ('upload_date', models.DateTimeField(db_column='upload_Date')),
                ('file_path', models.CharField(max_length=30)),
                ('index_num', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.ForeignKey(db_column='customer_name', on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customerlist')),
            ],
            options={
                'db_table': 'InspectionDocuments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AndroidOptions',
            fields=[
                ('package_name', models.OneToOneField(db_column='package_name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='customer.packages')),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('check_root', models.BooleanField(default=False)),
                ('detect_magisk', models.BooleanField(default=False)),
                ('check_integrity', models.BooleanField(default=False)),
                ('check_emul', models.BooleanField(default=False)),
                ('check_debugging', models.BooleanField(default=False)),
                ('prevent_debugging', models.BooleanField(default=False)),
                ('prevent_adb', models.BooleanField(default=False)),
                ('encrypt_so', models.BooleanField(default=False)),
                ('self_protect', models.BooleanField(default=False)),
                ('prevent_decompile', models.BooleanField(default=False)),
                ('chekc_mem_scanner', models.BooleanField(default=False)),
                ('encrypt_flutter', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Android_options',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IosInspectResult',
            fields=[
                ('package_name', models.OneToOneField(db_column='package_name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='customer.packages')),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=30, null=True)),
                ('jailbreak_test', models.BooleanField(default=False)),
                ('jailbreak', models.BooleanField(default=False)),
                ('integrity', models.BooleanField(default=False)),
                ('string_encrypt', models.BooleanField(default=False)),
                ('symbol_del', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'iOS_inspect_result',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IosOptions',
            fields=[
                ('package_name', models.OneToOneField(db_column='package_name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='customer.packages')),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('objc_string_encryption', models.BooleanField(default=False)),
                ('swift_string_encryption', models.BooleanField(default=False)),
                ('jailbreak_check', models.BooleanField(default=False)),
                ('threat_check', models.BooleanField(default=False)),
                ('integrity_check', models.BooleanField(default=False)),
                ('flex_3_check', models.BooleanField(default=False)),
                ('server_auth_manually', models.BooleanField(default=False)),
                ('objc_obfuscate', models.BooleanField(default=False)),
                ('swift_obfuscate', models.BooleanField(default=False)),
                ('symbol_delete', models.BooleanField(default=False)),
                ('log_hiding', models.BooleanField(default=False)),
                ('dynamic_api_hiding', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'iOS_options',
                'managed': True,
            },
        ),
    ]
