# Generated by Django 5.0.6 on 2024-08-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Manager',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InspectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('January', models.BooleanField(default=False)),
                ('February', models.BooleanField(default=False)),
                ('March', models.BooleanField(default=False)),
                ('April', models.BooleanField(default=False)),
                ('May', models.BooleanField(default=False)),
                ('June', models.BooleanField(default=False)),
                ('July', models.BooleanField(default=False)),
                ('August', models.BooleanField(default=False)),
                ('September', models.BooleanField(default=False)),
                ('October', models.BooleanField(default=False)),
                ('November', models.BooleanField(default=False)),
                ('December', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'InspectionSchedule',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='manger_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.manager'),
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=10)),
                ('license_expire_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'Packages',
                'managed': True,
                'unique_together': {('name', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='iOSInspectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_info', models.CharField(blank=True, max_length=30, null=True)),
                ('jailbreak_test', models.BooleanField(default=False)),
                ('jailbreak', models.BooleanField(default=False)),
                ('integrity', models.BooleanField(default=False)),
                ('string_encrypt', models.BooleanField(default=False)),
                ('symbol_del', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.packages')),
            ],
            options={
                'db_table': 'iOSInspectResult',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='iOSApplyOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objc_string_encryption', models.BooleanField(default=False)),
                ('swift_string_encryption', models.BooleanField(default=False)),
                ('jailbreak_check', models.BooleanField(default=False)),
                ('threat_check', models.BooleanField(default=False)),
                ('integrity_check', models.BooleanField(default=False)),
                ('flex_3_check', models.BooleanField(default=False)),
                ('server_auth_manually', models.BooleanField(default=False)),
                ('objc_obfuscate', models.BooleanField(default=False)),
                ('swift_obfuscate', models.BooleanField(default=False)),
                ('symbol_delete', models.BooleanField(default=False)),
                ('log_hiding', models.BooleanField(default=False)),
                ('dynamic_api_hiding', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.packages')),
            ],
            options={
                'db_table': 'iOSApplyOptions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField()),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.packages')),
            ],
            options={
                'db_table': 'InspectionRecord',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AndroidInspectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_info', models.CharField(blank=True, max_length=30, null=True)),
                ('rooting_test', models.BooleanField(default=False)),
                ('rooting', models.BooleanField(default=False)),
                ('integrity', models.BooleanField(default=False)),
                ('emulator', models.BooleanField(default=False)),
                ('obfuscate', models.BooleanField(default=False)),
                ('decompile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.packages')),
            ],
            options={
                'db_table': 'AndroidInspectResult',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AndroidApplyOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_root', models.BooleanField(default=False)),
                ('detect_magisk', models.BooleanField(default=False)),
                ('check_integrity', models.BooleanField(default=False)),
                ('check_emul', models.BooleanField(default=False)),
                ('check_debugging', models.BooleanField(default=False)),
                ('prevent_debugging', models.BooleanField(default=False)),
                ('prevent_adb', models.BooleanField(default=False)),
                ('encrypt_so', models.BooleanField(default=False)),
                ('self_protect', models.BooleanField(default=False)),
                ('prevent_decompile', models.BooleanField(default=False)),
                ('chekc_mem_scanner', models.BooleanField(default=False)),
                ('encrypt_flutter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.packages')),
            ],
            options={
                'db_table': 'AndroidApplyOptions',
                'managed': True,
            },
        ),
    ]
