# Generated by Django 5.0.6 on 2024-06-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlist',
            name='append_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
